### PR TITLE
Sign up revamping

### PR DESCRIPTION
**Pull request by Parastoo-S**
>> Revamped Sign up
>> Modified Edit User
>> Modified Login
>> Also made a minor change to booking to disapprove

### CODE REVIEW

**Comment by Parastoo-S** [comment]
@brunomrlima Hey, do you mind taking a quick look at this PR before I merge it? I revamped the sign up and login. The overall styling is still left which I will do at the very end. Also I still have not been able to figure out how to add the flash messages. I tried a couple of solutions but it didn't work. I will try again later but if you have a solution please let me know. Thanks!

**Comment by brunomrlima** [comment]
Hey Parastoo.

Try this in your 'application.html.slim' right before '= yield' (here will do for all the pages):
- flash.each do |type, message|
  - if type.eql?("notice")
    .alert.alert-success.center
      = message
  - if type.eql?("error")
    .alert.alert-danger.center
      = message
Now, if you want flash messages in only one specific page, add this code in that page.

**Comment by brunomrlima** [comment]
`- flash.each do |type, message|
  - if type.eql?("notice")
    .alert.alert-success.center
      = message
  - if type.eql?("error")
    .alert.alert-danger.center
      = message`

**Comment by brunomrlima** [comment]
God... This comments don't preserve indentations.... Just take care for the indentations for the code that I just sent. It should work well!

**Comment by brunomrlima** [comment]
Hey, Parastoo.

I created a new branch called 'flash'.

You can access it and then if you like the changes that I've made, just merge to the branch that you're working.

Flash seems to be working there.

**Comment by Parastoo-S** [comment]
Superrr. Thank you so much it works just right:D I will merge it in and merge this PR with the master.

**Comment by brunomrlima** [comment]
Great! : )

**Pull request merged**
